name: Check
on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]
jobs:
  detekt:
    name: Detekt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run Detekt
        run: |
          chmod +x gradlew
          ./gradlew detekt --stacktrace
        
      - name: Stop Gradle
        run: ./gradlew --stop
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run Debug Unit Tests
        run: |
          chmod +x gradlew
          ./gradlew test --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
  ui-tests:
    name: FTL UI Tests
    needs: [unit-tests, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build app and test APKs
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleDebug && ./gradlew  :app:assembleDebugAndroidTest

      - name: Stop Gradle
        run: ./gradlew --stop
